version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DB_HOST: mysql
    volumes:
      - .:/var/www
    depends_on:
      - mysql
    command: ["sh", "/var/www/docker/start-container.sh", "php-fpm"]

  mysql:
    image: mysql:8.0
    container_name: mysql_service_provider
    restart: unless-stopped
    env_file:
      - .env
    environment:
        DB_HOST: mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  web:
    image: nginx:alpine
    container_name: nginx_service_provider
    restart: unless-stopped
    ports:
      - "8001:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

volumes:
  mysql_data:
